import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    price: "300.00",
    color: "Blank and White",
    badge: true,
    des: "Stay cool and stylish with our boys' cap. Made from breathable fabric, it's perfect for outdoor adventures and everyday wear.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    price: "1800.00",
    color: "Gray",
    badge: true,
    des: " Elevate your living space with our sleek tea table. Crafted for both style and functionality, it's the perfect addition to your home decor.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "950.00",
    color: "Mixed",
    badge: true,
    des: " Immerse yourself in crystal-clear sound with our high-quality headphones. Designed for comfort and performance, they're your ticket to a superior audio experience.    ",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    price: "650.00",
    color: "Black",
    badge: true,
    des: "Shield your eyes in style with our trendy sunglasses. UV protection meets fashion-forward design for the perfect accessory on sunny days.    ",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Cap for Boys",
    price: "300.00",
    color: "Blank and White",
    badge: true,
    des: "Stay cool and stylish with our boys' cap. Made from breathable fabric, it's perfect for outdoor adventures and everyday wear.    ",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Tea Table",
    price: "1000.00",
    color: "Gray",
    badge: true,
    des: " Elevate your living space with our sleek tea table. Crafted for both style and functionality, it's the perfect addition to your home decor.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Headphones",
    price: "1000.00",
    color: "Mixed",
    badge: true,
    des: " Immerse yourself in crystal-clear sound with our high-quality headphones. Designed for comfort and performance, they're your ticket to a superior audio experience.    ",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Sun glasses",
    price: "1050.00",
    color: "Black",
    badge: true,
    des: "Shield your eyes in style with our trendy sunglasses. UV protection meets fashion-forward design for the perfect accessory on sunny days.    ",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "350.00",
    color: "Blank and White",
    badge: true,
    des: "Add a touch of elegance to your floral arrangements with our exquisite flower base. Its timeless design complements any bouquet.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "950.00",
    color: "Gray",
    badge: false,
    des: "Carry your essentials in style with our versatile backpack. Whether for school or a weekend getaway, it combines fashion and functionality seamlessly.    ",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Household materials",
    price: "600.00",
    color: "Mixed",
    badge: true,
    des: "  Explore our range of essential household materials designed to make daily chores a breeze. Quality meets convenience for a well-equipped home.    ",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "950.00",
    color: "Black",
    badge: false,
    des: " Pack your wanderlust essentials in our durable travel bag. With ample space and smart compartments, it's your perfect travel companion.    ",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "1500.00",
    color: "Black",
    badge: true,
    des: "Keep track of time in style with our round table clock. The perfect blend of functionality and aesthetics for any room.    ",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500.00",
    color: "Black",
    badge: true,
    des: "Stay connected and on top of your fitness goals with our feature-packed smartwatch. A sleek accessory that complements your active lifestyle.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "cloth Basket",
    price: "800.00",
    color: "Mixed",
    badge: true,
    des: "  Organize your space effortlessly with our cloth basket. Its sturdy design and chic appearance make it a must-have for any room.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "600.00",
    color: "Mixed",
    badge: false,
    des: "Delight your little ones with our collection of funny toys. Designed for both entertainment and development, they're a joy for babies and parents alike.",
  },
  {
    _id: 1013,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "600.00",
    color: "Mixed",
    badge: false,
    des: "Delight your little ones with our collection of funny toys. Designed for both entertainment and development, they're a joy for babies and parents alike.",
  },

  {
    _id: 1014,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2000.00",
    color: "Black",
    badge: true,
    des: "Stay connected and on top of your fitness goals with our feature-packed smartwatch. A sleek accessory that complements your active lifestyle.",
  },
  {
    _id: 1015,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "600.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1016,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500.00",
    color: "Black",
    badge: true,
    des: "Stay connected and on top of your fitness goals with our feature-packed smartwatch. A sleek accessory that complements your active lifestyle.",
  },
  {
    _id: 1017,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "950.00",
    color: "Black",
    badge: false,
    des: "  Pack your wanderlust essentials in our durable travel bag. With ample space and smart compartments, it's your perfect travel companion.    ",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "700.00",
    color: "Black",
    badge: true,
    des: "Keep track of time in style with our round table clock. The perfect blend of functionality and aesthetics for any room.",
  },
  {
    _id: 1019,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2000.00",
    color: "Black",
    badge: true,
    des: "Stay connected and on top of your fitness goals with our feature-packed smartwatch. A sleek accessory that complements your active lifestyle",
  },
  {
    _id: 1020,
    img: newArrThree,
    productName: "cloth Basket",
    price: "800.00",
    color: "Mixed",
    badge: true,
    des: "Organize your space effortlessly with our cloth basket. Its sturdy design and chic appearance make it a must-have for any room.",
  },
  {
    _id: 1021,
    img: spfThree,
    productName: "Headphones",
    price: "1000.00",
    color: "Mixed",
    badge: true,
    des: " Immerse yourself in crystal-clear sound with our high-quality headphones. Designed for comfort and performance, they're your ticket to a superior audio experience.    ",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "Sun glasses",
    price: "1050.00",
    color: "Black",
    badge: true,
    des: "Shield your eyes in style with our trendy sunglasses. UV protection meets fashion-forward design for the perfect accessory on sunny days.    ",
  },
  {
    _id: 1023,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "350.00",
    color: "Blank and White",
    badge: true,
    des: "Add a touch of elegance to your floral arrangements with our exquisite flower base. Its timeless design complements any bouquet.",
  },
  {
    _id: 1024,
    img: spfOne,
    productName: "Cap for Boys",
    price: "300.00",
    color: "Blank and White",
    badge: true,
    des: "Stay cool and stylish with our boys' cap. Made from breathable fabric, it's perfect for outdoor adventures and everyday wear.",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "Tea Table",
    price: "1800.00",
    color: "Gray",
    badge: true,
    des: "Elevate your living space with our sleek tea table. Crafted for both style and functionality, it's the perfect addition to your home decor.",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Headphones",
    price: "1000.00",
    color: "Mixed",
    badge: true,
    des: " Immerse yourself in crystal-clear sound with our high-quality headphones. Designed for comfort and performance, they're your ticket to a superior audio experience.    ",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "Sun glasses",
    price: "2200.00",
    color: "Black",
    badge: true,
    des: "Shield your eyes in style with our trendy sunglasses. UV protection meets fashion-forward design for the perfect accessory on sunny days.    ",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "350.00",
    color: "Blank and White",
    badge: true,
    des: "Add a touch of elegance to your floral arrangements with our exquisite flower base. Its timeless design complements any bouquet.",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "1800.00",
    color: "Gray",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Household materials",
    price: "2500.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "950.00",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "1230.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "cloth Basket",
    price: "800.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "600.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "600.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "600.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "950.00",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "900.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2000.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "cloth Basket",
    price: "800.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Headphones",
    price: "1000.00",
    color: "Mixed",
    badge: true,
    des: " Immerse yourself in crystal-clear sound with our high-quality headphones. Designed for comfort and performance, they're your ticket to a superior audio experience.    ",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Sun glasses",
    price: "2000.00",
    color: "Black",
    badge: true,
    des: "Shield your eyes in style with our trendy sunglasses. UV protection meets fashion-forward design for the perfect accessory on sunny days.    ",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "350.00",
    color: "Blank and White",
    badge: true,
    des: "Add a touch of elegance to your floral arrangements with our exquisite flower base. Its timeless design complements any bouquet.",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Cap for Boys",
    price: "350.00",
    color: "Blank and White",
    badge: true,
    des: "Stay cool and stylish with our boys' cap. Made from breathable fabric, it's perfect for outdoor adventures and everyday wear.",
  },
];
// =================== PaginationItems End here =================
